import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { useSimulation } from '@/store/simulation';
import TrustEngineViz from '@/components/workflow/TrustEngineViz';
import ConfidenceSlider from '@/components/workflow/ConfidenceSlider';
import BrandButton from '@/components/ui/BrandButton';
import { AlertTriangle, Ban, Lock, Cpu, Check, X } from 'lucide-react';
export const TrustPage = () => {
    const navigate = useNavigate();
    const { confidence, setConfidence, getTrustPolicy, reset, advanceState } = useSimulation();
    const policy = getTrustPolicy(confidence);
    const isWarningState = policy === 'confirm' || policy === 'blocked';
    return (_jsx("div", { className: "w-full min-h-screen bg-[#07080C] text-white pt-28 pb-20 px-6 md:px-12 select-none", children: _jsxs("div", { className: "max-w-7xl mx-auto w-full", children: [_jsxs("div", { className: "border-b border-white/10 pb-8 mb-12", children: [_jsxs("div", { className: "flex items-center gap-3 font-display text-xs tracking-widest text-mint uppercase mb-3 font-bold", children: [_jsx("span", { children: "/06 DETERMINISTIC GOVERNANCE" }), _jsx("span", { className: "text-white/20", children: "\u2022" }), _jsx("span", { className: "text-white/60", children: "TRUST & SAFETY MATRIX" })] }), _jsxs("h1", { className: "font-display text-5xl sm:text-7xl lg:text-8xl font-black tracking-tight text-white leading-[0.92] mb-4", children: ["AUTONOMY", _jsx("br", {}), "NEEDS", _jsx("br", {}), _jsx("span", { className: "text-transparent bg-clip-text bg-gradient-to-r from-mint via-cobalt to-violet", children: "A BRAKE." })] }), _jsx("p", { className: "text-base sm:text-xl text-white/70 font-sans max-w-xl leading-relaxed", children: "Confidence before autonomy. The on-device Trust Engine evaluates intent, schema validity, and risk before any action touches host computer applications." })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-10 items-center mb-16", children: [_jsxs("div", { className: "lg:col-span-5 space-y-6", children: [_jsx(ConfidenceSlider, {}), _jsxs("div", { className: "p-6 rounded-2xl bg-[#0C0E14] border border-white/10", children: [_jsx("span", { className: "text-[10px] font-mono text-white/40 uppercase tracking-widest block mb-2", children: "SIMULATE AMBIGUITY" }), _jsxs("div", { className: "flex items-center justify-between gap-4", children: [_jsx("span", { className: "text-xs font-sans text-white/70", children: "Test failure mode threshold (63% User Confirmation Required)" }), _jsx("button", { onClick: () => setConfidence(63.0), className: "px-4 py-2 rounded-xl bg-amber-warm/15 hover:bg-amber-warm/25 border border-amber-warm/40 text-amber-warm font-mono text-xs font-bold transition-all flex-shrink-0", children: "TEST 63%" })] })] }), _jsx(AnimatePresence, { children: isWarningState && (_jsxs(motion.div, { initial: { opacity: 0, y: 15 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -15 }, className: `p-6 rounded-2xl border ${policy === 'blocked' ? 'bg-coral/10 border-coral/40' : 'bg-amber-warm/10 border-amber-warm/40'}`, children: [_jsxs("div", { className: "flex items-center gap-3 mb-3", children: [policy === 'blocked' ? (_jsx(Ban, { className: "w-5 h-5 text-coral" })) : (_jsx(AlertTriangle, { className: "w-5 h-5 text-amber-warm" })), _jsx("h4", { className: "font-display font-bold text-sm tracking-wider uppercase", children: policy === 'blocked' ? 'ACTION BLOCKED' : 'USER CONFIRMATION REQUIRED' })] }), _jsx("p", { className: "text-xs font-sans text-white/80 leading-relaxed mb-4", children: policy === 'blocked'
                                                    ? 'Model confidence is below the safety floor (55%). Automated action has been completely suppressed by the Trust Engine.'
                                                    : 'Semantic ambiguity detected in target parameters. Human confirmation is mandatory before dispatching commands to Jira.' }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("button", { onClick: reset, className: "px-4 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-white font-mono text-xs font-bold transition-all flex items-center gap-1.5", children: [_jsx(X, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "REJECT ACTION" })] }), policy !== 'blocked' && (_jsxs("button", { onClick: advanceState, className: "px-4 py-2 rounded-xl bg-amber-warm hover:bg-amber-warm/90 text-[#07080C] font-mono text-xs font-bold transition-all flex items-center gap-1.5", children: [_jsx(Check, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "CONFIRM DISPATCH" })] }))] })] })) })] }), _jsxs("div", { className: "lg:col-span-7 flex flex-col items-center justify-center relative min-h-[480px]", children: [_jsx("div", { className: `absolute w-88 h-88 rounded-full blur-[100px] pointer-events-none transition-colors duration-500 ${policy === 'auto'
                                        ? 'bg-mint/15'
                                        : policy === 'assisted'
                                            ? 'bg-cobalt/15'
                                            : policy === 'confirm'
                                                ? 'bg-amber-warm/15'
                                                : 'bg-coral/15'}` }), _jsx("div", { className: "relative z-10", children: _jsx(TrustEngineViz, {}) }), _jsxs("div", { className: "mt-6 flex items-center gap-6 font-mono text-xs text-white/40", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Lock, { className: "w-3.5 h-3.5 text-mint" }), _jsx("span", { children: "AIR-GAPPED GOVERNANCE" })] }), _jsx("span", { children: "\u2022" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Cpu, { className: "w-3.5 h-3.5 text-violet" }), _jsx("span", { children: "NPU AUDIT TRAIL" })] })] })] })] }), _jsxs("div", { className: "p-10 rounded-3xl bg-[#0C0E14] border border-white/10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6", children: [_jsxs("div", { children: [_jsx("span", { className: "font-mono text-xs text-mint font-bold uppercase tracking-wider", children: "NEXT DESTINATION" }), _jsx("h3", { className: "font-display text-2xl sm:text-3xl font-bold text-white mt-1", children: "OBSERVE THE WHOLE SYSTEM" }), _jsx("p", { className: "text-white/60 text-sm font-sans mt-1", children: "Watch the full 12-state simulation think and execute in 1.8 seconds." })] }), _jsx(BrandButton, { variant: "primary", size: "lg", onClick: () => navigate('/demo'), className: "flex-shrink-0", children: "RUN LIVE DEMO" })] })] }) }));
};
export default TrustPage;
