import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { DEMO_METRICS } from '@/data/mockData';
import { useSimulation } from '@/store/simulation';
import GlassPanel from '@/components/ui/GlassPanel';
import { CheckCircle2 } from 'lucide-react';
const MetricCard = ({ value, label, delay = 0, suffix = '' }) => (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay, type: 'spring' }, children: _jsxs(GlassPanel, { className: "p-6 flex flex-col items-center justify-center text-center h-full hover:border-cyan-500/50 transition-colors", children: [_jsxs("div", { className: "text-3xl font-light text-white mb-2 flex items-baseline gap-1", children: [value, suffix && _jsx("span", { className: "text-lg text-gray-500", children: suffix })] }), _jsx("div", { className: "text-[10px] font-mono text-cyan-400 tracking-widest uppercase", children: label })] }) }));
export default function SuccessState() {
    const { confidence } = useSimulation();
    return (_jsxs("div", { className: "w-full max-w-4xl flex flex-col items-center gap-10", children: [_jsxs(motion.div, { initial: { scale: 0.8, opacity: 0 }, animate: { scale: 1, opacity: 1 }, transition: { type: 'spring', bounce: 0.5 }, className: "flex flex-col items-center text-center", children: [_jsx("div", { className: "w-20 h-20 rounded-full bg-green-500/20 border-2 border-green-500 flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(34,197,94,0.4)]", children: _jsx(CheckCircle2, { className: "w-10 h-10 text-green-400" }) }), _jsx("h2", { className: "text-4xl font-light text-white mb-2", children: "CONTEXT \u2192 ACTION" }), _jsx("div", { className: "text-sm font-mono text-gray-400 tracking-[0.3em]", children: "WORKFLOW COMPLETE" })] }), _jsxs("div", { className: "grid grid-cols-3 gap-6 w-full", children: [_jsx(MetricCard, { value: DEMO_METRICS.appSwitchesAvoided, label: "App Switches Avoided", delay: 0.2 }), _jsx(MetricCard, { value: DEMO_METRICS.manualFieldsEliminated, label: "Manual Fields Eliminated", delay: 0.3 }), _jsx(MetricCard, { value: confidence.toFixed(1), suffix: "%", label: "AI Confidence", delay: 0.4 }), _jsx(MetricCard, { value: DEMO_METRICS.inference, label: "Inference", delay: 0.5 }), _jsx(MetricCard, { value: DEMO_METRICS.cloudRequests, label: "Cloud Requests", delay: 0.6 }), _jsx(MetricCard, { value: DEMO_METRICS.workflowLatency, suffix: "s", label: "Total Workflow Latency", delay: 0.7 })] }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 1 }, className: "text-[10px] text-gray-600 font-mono tracking-widest mt-4 uppercase", children: "Prototype Demonstration Metrics" })] }));
}
