import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { useSimulation } from '@/store/simulation';
import TrustEngineViz from '@/components/workflow/TrustEngineViz';
import ConfidenceSlider from '@/components/workflow/ConfidenceSlider';
import { Cpu, Lock } from 'lucide-react';
export const TrustSection = () => {
    const { confidence, getTrustPolicy } = useSimulation();
    const policy = getTrustPolicy(confidence);
    return (_jsxs("section", { id: "trust", className: "relative min-h-screen bg-ink text-white flex flex-col justify-between py-28 px-6 md:px-12 overflow-hidden select-none border-t border-white/5", children: [_jsxs("div", { className: "max-w-7xl mx-auto w-full flex items-center justify-between border-b border-white/10 pb-6 mb-12", children: [_jsxs("div", { className: "flex items-center gap-3 font-mono text-xs tracking-widest text-white/50 uppercase", children: [_jsx("span", { className: "font-bold text-mint", children: "/06" }), _jsx("span", { children: "TRUST ENGINE" })] }), _jsx("div", { className: "font-mono text-xs tracking-widest text-white/40 hidden sm:block uppercase", children: "GOVERNANCE BEFORE EXECUTION" })] }), _jsx("div", { className: "relative z-10 max-w-7xl mx-auto w-full flex-1 flex flex-col justify-center my-auto", children: _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-12 items-center", children: [_jsxs("div", { className: "lg:col-span-5", children: [_jsxs(motion.h2, { initial: { opacity: 0, y: 30 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] }, className: "font-display text-5xl sm:text-7xl md:text-8xl font-black tracking-tighter text-white leading-[0.92] mb-6", children: ["CONFIDENCE", _jsx("br", {}), "BEFORE", _jsx("br", {}), _jsx("span", { className: "text-transparent bg-clip-text bg-gradient-to-r from-mint via-cobalt to-violet", children: "AUTONOMY." })] }), _jsx(motion.p, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.8, delay: 0.2 }, className: "text-base sm:text-xl text-white/80 font-normal leading-relaxed max-w-lg mb-8 font-sans", children: "Not every decision deserves automatic execution." }), _jsx("div", { className: "max-w-md", children: _jsx(ConfidenceSlider, {}) })] }), _jsxs("div", { className: "lg:col-span-7 flex flex-col items-center justify-center relative min-h-[460px]", children: [_jsx("div", { className: `absolute w-80 h-80 rounded-full blur-[100px] pointer-events-none transition-colors duration-500 ${policy === 'auto'
                                        ? 'bg-mint/15'
                                        : policy === 'assisted'
                                            ? 'bg-cobalt/15'
                                            : policy === 'confirm'
                                                ? 'bg-amber-warm/15'
                                                : 'bg-coral/15'}` }), _jsx("div", { className: "relative z-10 flex items-center justify-center p-4", children: _jsx(TrustEngineViz, {}) }), _jsxs("div", { className: "mt-4 flex items-center gap-6 font-mono text-[11px] text-white/40", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Lock, { className: "w-3.5 h-3.5 text-mint" }), _jsx("span", { children: "DETERMINISTIC GATE" })] }), _jsx("span", { children: "\u2022" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Cpu, { className: "w-3.5 h-3.5 text-violet" }), _jsx("span", { children: "NPU COPROCESSOR LINKED" })] })] })] })] }) }), _jsxs("div", { className: "max-w-7xl mx-auto w-full pt-10 border-t border-white/10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 font-mono text-xs text-white/40", children: [_jsx("span", { children: "\u201CNO GHOST ACTIONS.\u201D" }), _jsx("span", { children: "CONTINUOUS MATHEMATICAL VERIFICATION BEFORE UI DISPATCH" })] })] }));
};
export default TrustSection;
